global:
  scrape_interval: 3s

  external_labels:
    monitor: "example-app"

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "example"
    static_configs:
      - targets: ["app:5000"]
